name: Java Format Check

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**/*.java' # Only trigger for Java file changes

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the PR code
      - name: Checkout code
        uses: actions/checkout@v3 

      # Step 2: Set up Java (if needed for format check tools)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Fetch latest changes
      - name: Fetch latest changes
        run: git fetch origin

      # Step 4: Get a list of changed Java files in the PR
      - name: Get changed Java files
        id: changed_files
        run: |
          echo "::group::Changed Java Files"
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep '\.java$' || true)
          echo "$CHANGED_FILES"
          echo "::endgroup::"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo $CHANGED_FILES

      # Step 5: Check formatting of the changed files
      - name: Check Java file format
        run: |
          if [ -z "${{ env.CHANGED_FILES }}" ]; then
            echo "No Java files changed."
          else
            for FILE in ${{ env.CHANGED_FILES }}; do
              FILE_NAME=$(basename "$FILE")
              echo "Checking for $FILE_NAME"
              mvn formatter:validate -f formatter-pom.xml "-Dformatter.includes=**/$FILE_NAME"
            done
          fi
